#!/usr/bin/env python3
"""architecture-harvest.py — harvest the decisions of the ARDs on the specs repository's
default branch into the team architecture knowledge base, <specs>/architecture/.

Run by the harvest-decisions command; the format it writes is the plugin's
architecture-kb reference, and a change to either is a change to both. Python
standard library only.

  architecture-harvest.py --specs <root> --ref <ref> [--layout vi|prd] [--dry-run]
  architecture-harvest.py --specs <root> --ref <ref> --pending-kb
  architecture-harvest.py --selftest

<root> is the specs repository's top level. Every input — the ARDs, the files that
cite their decisions and the records already written — is read from <ref> with git,
never from the working tree, so an uncommitted or unmerged ARD is never harvested.
The plan prints as JSON; without --dry-run it is also written into
<root>/architecture/ in the working tree, and never outside it. Nothing is ever deleted.
--pending-kb lists the kb/ branches not yet on <ref> — neither its ancestors nor carrying an
architecture/ tree it has held, which is what a squash or rebase merge leaves.

Layouts: `vi` — <KEY>_ARD.md and <EPIC>-<area>_ARD.md under specifications/<VI>-<slug>/;
`prd` — ard.md and ard-<area>.md in PRD-<KEY>-<slug>/ and EPIC-<KEY>-<slug>/ folders.

Exit 0: it ran — problems are listed in the plan, never signalled by the exit code.
Exit 2: it could not run (not a repository's top level, an unknown ref, any unexpected
error). --selftest builds its fixtures in temporary repositories at run time.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile

KB = "architecture"
EXCLUDED_DIRS = {"revisions", "dev-workflows", "attachments"}  # and any *-import/ folder: a tracker export
LABELS = ("Binds", "Prevents", "Rule", "Alternatives", "Supersedes", "Superseded by", "Withdrawn")
LABEL_RE = re.compile(r"\*\*(%s):\*\*" % "|".join(re.escape(x) for x in LABELS))
HEADING_RE = re.compile(r"^###\s+\[AD[#-](\d+)\]:\s*(.*?)\s*$")
HEADING_ANY_RE = re.compile(r"^###\s+\[AD")
HEADING_NOCOLON_RE = re.compile(r"^###\s+\[AD[#-]\d+\](?!:)")
HEADING_NOBRACKET_RE = re.compile(r"^###\s+AD[#-]\d+")
SECTION_RE = re.compile(r"^##\s+(?:\d+\.\s*)?Architecture decisions\s*$", re.I)
TOP_HEADING_RE = re.compile(r"^#{1,2}\s")
CITE_RE = re.compile(r"\[AD[#-](\d+)\]")
DEVIATION_RE = re.compile(r"^\s*[-*]\s*ARD deviation:\s*\[AD[#-](\d+)\]\s*(.*?)\s*$")
KEY = r"[A-Z][A-Z0-9_]*(?:-\d+)+"
KEY_RE = re.compile("^%s$" % KEY)
RECORD_ID = KEY + r"(?:-[a-z0-9]+)*-AD\d+"
SUPERSEDES_RE = re.compile(r"\[((%s)\b[^\]]*)\]\(([^)]*)\)" % RECORD_ID)
VI_ARD_RE = re.compile(r"^([A-Z][A-Z0-9_]*-\d+)(?:-([a-z0-9][a-z0-9-]*))?_ARD\.md$")
VI_FOLDER_RE = re.compile(r"^([A-Z][A-Z0-9_]*-\d+)")
PRD_ARD_RE = re.compile(r"^ard(?:-([a-z0-9][a-z0-9-]*))?\.md$")
KIND_FOLDER_RE = re.compile(r"^(BRD|PRD|EPIC)-(%s)(?=-|$)" % KEY)
GENERATED = "<!-- Generated by /harvest-decisions from the source ARD — change the ARD, not this file. -->"
OWNED = ("id", "title", "type", "status", "scope", "vi", "prd", "epic", "source", "components", "tags", "superseded_by")
GROUP = {"vi": ("vi", "VI"), "prd": ("prd", "PRD")}


class Abort(Exception):
    """The run cannot proceed: exit 2."""


def problem(kind, path, line, detail):
    return {"kind": kind, "file": path, "line": line, "detail": detail}


def git(root, *args):
    r = subprocess.run(["git", "-C", root, "-c", "core.quotePath=false", *args],
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if r.returncode != 0:
        raise Abort("git %s: %s" % (" ".join(args), r.stderr.decode("utf-8", "replace").strip()))
    return r.stdout.decode("utf-8", "replace")


def resolve(root, ref):
    """The full sha <ref> names, once <root> is proven to be a repository's top level."""
    if not os.path.isdir(root):
        raise Abort("%s is not a directory" % root)
    try:
        top = git(root, "rev-parse", "--show-toplevel").strip()
    except Abort:
        raise Abort("%s is not a git repository" % root)
    if os.path.realpath(top) != os.path.realpath(root):
        raise Abort("%s is not its repository's top level (%s is)" % (root, top))
    try:
        return git(root, "rev-parse", "--verify", "--quiet", ref + "^{commit}").strip()
    except Abort:
        raise Abort("unknown ref %s" % ref)


def list_files(root, sha):
    return [p for p in git(root, "ls-tree", "-r", "-z", "--name-only", sha).split("\0") if p]


def read(root, sha, path):
    return git(root, "show", "%s:%s" % (sha, path))


def natural(s):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", s)]


def excluded(path):
    """A folder never read: a reserved one, or a tracker export — an *-import/ folder carrying no key,
    so a feature or Epic folder whose slug merely ends in -import is still read."""
    for part in path.split("/")[:-1]:
        if part in EXCLUDED_DIRS:
            return True
        if part.endswith("-import") and not VI_FOLDER_RE.match(part) and not KIND_FOLDER_RE.match(part):
            return True
    return False


# --- frontmatter -------------------------------------------------------------------------

def split_frontmatter(text):
    lines = text.split("\n")
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return lines[1:i], lines[i + 1:]
    return [], lines


def fm_blocks(fm_lines):
    """Top-level keys in order, and each key's lines (its own and its indented continuation)."""
    order, blocks, cur = [], {}, None
    for ln in fm_lines:
        m = re.match(r"^([A-Za-z_][\w-]*):", ln)
        if m:
            cur = m.group(1)
            if cur not in blocks:
                order.append(cur)
            blocks[cur] = [ln]
        elif cur is not None:
            blocks[cur].append(ln)
    return order, blocks


def unquote(v):
    v = v.strip()
    if v.startswith('"'):
        try:
            return json.loads(v)
        except ValueError:
            return v.strip('"')
    if len(v) >= 2 and v[0] == v[-1] == "'":
        return v[1:-1]
    return v


def fm_scalar(blocks, key, strip_comment=True):
    if key not in blocks:
        return None
    v = blocks[key][0].split(":", 1)[1]
    if strip_comment and not v.strip().startswith('"'):
        v = re.sub(r"\s+#.*$", "", v)
    v = unquote(v)
    return None if v in ("", "null", "~") else v


def fm_list(blocks, key):
    """A flow list on the key's line, or the `- item` lines below it."""
    if key not in blocks:
        return []
    head = blocks[key][0].split(":", 1)[1].strip()
    if head.startswith("["):
        try:
            return [str(x) for x in json.loads(head)]
        except ValueError:
            return [unquote(x) for x in head.strip("[]").split(",") if x.strip()]
    out = []
    for ln in blocks[key][1:]:
        m = re.match(r"^\s*-\s*(.+?)\s*$", ln)
        if m:
            out.append(unquote(re.sub(r"\s+#.*$", "", m.group(1))))
    return out


def component_ids(blocks):
    ids = []
    for ln in blocks.get("components", [])[1:]:
        m = re.match(r"^\s*(?:-\s*)?id:\s*(.+?)\s*$", ln)
        if m:
            ids.append(unquote(re.sub(r"\s+#.*$", "", m.group(1))))
    return ids


# --- discovery ---------------------------------------------------------------------------

def discover_vi(files):
    ards, problems = [], []
    for p in files:
        parts = p.split("/")
        if len(parts) < 3 or parts[0] != "specifications" or excluded(p):
            continue
        m = VI_ARD_RE.match(parts[-1])
        if not m:
            continue
        fk = VI_FOLDER_RE.match(parts[1])
        if not fk:
            problems.append(problem("unparseable", p, 0, "its feature folder %s carries no key" % parts[1]))
            continue
        key, area, group = m.group(1), m.group(2), fk.group(1)
        if area:
            scope, skey, epic = "area", "%s-%s" % (key, area), key
        elif key == group:
            scope, skey, epic = "vi", key, None
        else:
            scope, skey, epic = "epic", key, key
        ards.append({"path": p, "key": skey, "scope": scope, "group": group, "epic": epic,
                     "folder": "/".join(parts[:2])})
    return ards, problems


def own_key(root, sha, path, fallback):
    _, blocks = fm_blocks(split_frontmatter(read(root, sha, path))[0])
    return fm_scalar(blocks, "key") or fallback


def folder_key(root, sha, folder, present):
    for name in ("prd.md", "ard.md"):
        if folder + "/" + name in present:
            k = own_key(root, sha, folder + "/" + name, None)
            if k and KEY_RE.match(k):
                return k
    return KIND_FOLDER_RE.match(folder.rsplit("/", 1)[-1]).group(2)


def discover_prd(root, sha, files, present):
    ards, problems = [], []
    for p in files:
        parts = p.split("/")
        if len(parts) < 3 or parts[0] != "specifications" or excluded(p):
            continue
        m = PRD_ARD_RE.match(parts[-1])
        if not m:
            continue
        km = KIND_FOLDER_RE.match(parts[-2])
        if not km or km.group(1) == "BRD":
            problems.append(problem("unparseable", p, 0, "an ARD outside a PRD- or EPIC- folder"))
            continue
        prd_i = next((i for i in range(len(parts) - 2, 0, -1)
                      if parts[i].startswith("PRD-") and KIND_FOLDER_RE.match(parts[i])), None)
        if prd_i is None:
            problems.append(problem("unparseable", p, 0, "no PRD- folder holds this ARD"))
            continue
        folder = "/".join(parts[:prd_i + 1])
        key = own_key(root, sha, p, km.group(2))
        if not KEY_RE.match(key):
            problems.append(problem("unparseable", p, 0, "its key: %s is not a key" % key))
            continue
        area, kind = m.group(1), km.group(1)
        if area:
            scope, skey, epic = "area", "%s-%s" % (key, area), (key if kind == "EPIC" else None)
        elif kind == "PRD":
            scope, skey, epic = "prd", key, None
        else:
            scope, skey, epic = "epic", key, key
        ards.append({"path": p, "key": skey, "scope": scope, "group": folder_key(root, sha, folder, present),
                     "epic": epic, "folder": folder})
    return ards, problems


# --- parsing -----------------------------------------------------------------------------

def parse_fields(body):
    fields = {"Supersedes": []}
    found = list(LABEL_RE.finditer(body))
    for i, m in enumerate(found):
        end = found[i + 1].start() if i + 1 < len(found) else len(body)
        value = re.sub(r"\s*·\s*$", "", body[m.end():end].strip()).strip()
        value = re.sub(r"\n\s*[-*+]$", "", value).strip()  # the next field's bullet marker, in bullet-form fields
        if m.group(1) == "Supersedes":
            fields["Supersedes"].append(value)
        elif m.group(1) not in fields:
            fields[m.group(1)] = value
    return fields


def validate(n, f):
    if not f.get("Rule"):
        return "[AD#%d] has no **Rule:**" % n
    if f.get("Superseded by") and f.get("Withdrawn"):
        return "[AD#%d] is both superseded and withdrawn" % n
    if f.get("Superseded by") and not CITE_RE.search(f["Superseded by"]):
        return "[AD#%d]'s **Superseded by:** names no [AD#M]" % n
    for v in f["Supersedes"]:
        if not SUPERSEDES_RE.match(v):
            return "[AD#%d]'s **Supersedes:** is not a link whose text starts with a record id" % n
    return None


def parse_ard(text, path):
    fm, lines = split_frontmatter(text)
    offset = len(text.split("\n")) - len(lines)
    _, blocks = fm_blocks(fm)
    title = fm_scalar(blocks, "title", strip_comment=False)
    if not title:
        title = next((ln[2:].strip() for ln in lines if ln.startswith("# ")), os.path.basename(path))
    problems, raw, in_section, cur, found = [], [], False, None, False
    for i, ln in enumerate(lines, offset + 1):
        if TOP_HEADING_RE.match(ln):
            if cur:
                raw.append(cur)
                cur = None
            in_section = bool(SECTION_RE.match(ln))
            found = found or in_section
            continue
        if not in_section:
            continue
        if ln.startswith("### "):
            if cur:
                raw.append(cur)
                cur = None
            m = HEADING_RE.match(ln)
            if m:
                cur = {"n": int(m.group(1)), "title": m.group(2), "line": i, "body": []}
            elif HEADING_NOCOLON_RE.match(ln):
                problems.append(problem("unparseable", path, i, "a decision heading with no colon after its number — write `### [AD#N]: <title>`"))
            elif HEADING_NOBRACKET_RE.match(ln):
                problems.append(problem("unparseable", path, i, "a decision heading without brackets — write `### [AD#N]: <title>`"))
            elif HEADING_ANY_RE.match(ln):
                problems.append(problem("unparseable", path, i, "a decision heading with no number"))
            continue
        if cur is not None:
            cur["body"].append(ln)
    if cur:
        raw.append(cur)
    if not found:
        problems.append(problem("unparseable", path, 0, "no `## Architecture decisions` section"))
    counts = {}
    for d in raw:
        counts[d["n"]] = counts.get(d["n"], 0) + 1
    seen, decisions = set(), []
    for d in raw:
        if counts[d["n"]] > 1:
            if d["n"] in seen:
                problems.append(problem("unparseable", path, d["line"], "[AD#%d] appears twice in this ARD" % d["n"]))
            seen.add(d["n"])
            continue
        f = parse_fields("\n".join(d["body"]))
        bad = validate(d["n"], f)
        if not bad and f.get("Superseded by"):
            m_ = int(CITE_RE.search(f["Superseded by"]).group(1))
            if m_ not in counts:
                bad = "[AD#%d]'s **Superseded by:** names [AD#%d], which this ARD does not hold" % (d["n"], m_)
        if bad:
            problems.append(problem("unparseable", path, d["line"], bad))
            continue
        d["fields"] = f
        decisions.append(d)
    return {"title": title, "blocks": blocks, "decisions": decisions, "numbers": {d["n"] for d in raw}}, problems


# --- rendering ---------------------------------------------------------------------------

def q(s):
    return json.dumps(s, ensure_ascii=False)


def flow(items):
    return "[" + ", ".join(q(x) for x in items) + "]"


def link(path):
    target = "../../" + path
    return "<%s>" % target if re.search(r"[\s()<>]", target) else target


def render_record(r, preserved, group_key):
    fm = ["---", "id: " + r["id"], "title: " + q(r["title"]), "type: decision", "status: " + r["status"],
          "scope: " + r["scope"], "%s: %s" % (group_key, r["group"]), "epic: " + (r["epic"] or "null"),
          "source: " + q(r["source"]), "components: " + flow(r["components"]), "tags: " + flow(r["tags"])]
    if r["superseded_by"]:
        fm.append("superseded_by: " + r["superseded_by"])
    for block in preserved:
        fm.extend(block)
    fm.append("---")
    f = r["fields"]
    out = fm + [GENERATED, "# %s: %s" % (r["id"], r["title"]), ""]
    for label in ("Binds", "Prevents", "Rule", "Alternatives"):
        if f.get(label):
            out += ["**%s:** %s" % (label, f[label]), ""]
    for v in f["Supersedes"]:
        m = SUPERSEDES_RE.match(v)
        out += ["**Supersedes:** [%s](%s.md)%s" % (m.group(1), m.group(2), v[m.end():]), ""]
    if f.get("Superseded by"):
        out += ["**Superseded by:** " + f["Superseded by"], ""]
    elif r["cross"]:
        out += [r["cross"], ""]
    if f.get("Withdrawn"):
        out += ["**Withdrawn:** " + f["Withdrawn"], ""]
    out += ["Source: [%s, [AD#%d]](%s)" % (r["ard_title"], r["n"], link(r["source"])), "", "## Applied in", ""]
    out += ["- [%s](%s)" % (p, link(p)) for p in sorted(r["applied"])] or ["None."]
    out += ["", "## Deviated in", ""]
    out += ["- [%s](%s) — %s" % (p, link(p), t) for p, t in r["deviated"]] or ["None."]
    return "\n".join(out) + "\n"


def render_index(entries):
    out = ["# Generated by /harvest-decisions from the ARDs on the specs repository's default branch — do not edit.",
           "artifacts:"]
    for e in entries:
        out += ["  - id: " + e["id"], "    type: decision", "    title: " + q(e["title"]), "    status: " + e["status"],
                "    path: decisions/%s.md" % e["id"], "    tags: " + flow(e["tags"])]
    return "\n".join(out) + "\n"


def render_readme(entries, group_word):
    live = [e for e in entries if e["status"] == "accepted"]
    out = ["# Architecture knowledge base", "",
           "The team's architecture decisions: one record per `[AD#N]` of the ARDs on the specs repository's default "
           "branch. `/create-ard`, `/specify` and `/design` ground on the live ones, and a later ARD departs from one only with "
           "`**Supersedes:**`. Every file here is generated by `/harvest-decisions` — to change a decision, refine "
           "its ARD and harvest again; never edit a record by hand.", ""]
    if live:
        out += ["| Record | Title | %s |" % group_word, "|---|---|---|"]
        out += ["| [%s](decisions/%s.md) | %s | %s |" % (e["id"], e["id"], e["title"].replace("|", "\\|"), e["group"])
                for e in live]
    else:
        out += ["No live records."]
    n = {s: sum(1 for e in entries if e["status"] == s) for s in ("accepted", "superseded", "withdrawn")}
    out += ["", "%d live · %d superseded · %d withdrawn." % (n["accepted"], n["superseded"], n["withdrawn"])]
    return "\n".join(out) + "\n"


# --- the harvest -------------------------------------------------------------------------

def resolve_citation(n, entry, group_ard, parsed):
    """The ARD a cited [AD#n] means: the Epic ARD, else exactly one area ARD, else the group-level ARD."""
    def has(a):
        return a is not None and n in parsed[a["path"]]["numbers"]
    if entry:
        if has(entry["epic"]):
            return entry["epic"], False
        hits = [a for a in entry["areas"] if has(a)]
        if len(hits) == 1:
            return hits[0], False
        if len(hits) > 1:
            return None, True
    return (group_ard, False) if has(group_ard) else (None, False)


def harvest(root, ref, layout="vi", write=False):
    group_key, group_word = GROUP[layout]
    sha = resolve(root, ref)
    files = list_files(root, sha)
    present = set(files)
    ards, problems = discover_vi(files) if layout == "vi" else discover_prd(root, sha, files, present)
    plan = {"ref": ref, "sha": sha, "layout": layout, "no_ards": not ards, "create": [], "update": [],
            "supersede": [], "withdraw": [], "unchanged": [], "kept": [], "files": [], "problems": problems, "live": 0}
    if not ards:
        return plan

    by_key = {}
    for a in ards:
        by_key.setdefault(a["key"], []).append(a)
    for a in ards:
        others = [x["path"] for x in by_key[a["key"]] if x is not a]
        if others:
            problems.append(problem("key-conflict", a["path"], 0, "scope key %s is also %s" % (a["key"], ", ".join(others))))
    ards = [a for a in ards if len(by_key[a["key"]]) == 1]

    parsed = {}
    for a in ards:
        parsed[a["path"]], probs = parse_ard(read(root, sha, a["path"]), a["path"])
        problems.extend(probs)
    group_ard, by_dir = {}, {}
    for a in ards:
        if a["scope"] == group_key:
            group_ard[a["group"]] = a
        else:
            e = by_dir.setdefault(os.path.dirname(a["path"]), {"epic": None, "areas": []})
            if a["scope"] == "epic":
                e["epic"] = a
            else:
                e["areas"].append(a)

    records = {}
    for a in ards:
        info = parsed[a["path"]]
        ga = group_ard.get(a["group"])
        comps = component_ids(parsed[ga["path"]]["blocks"]) if ga else []
        slugs = [s.split("@")[0].strip() for s in fm_list(info["blocks"], "grounded_repos")]
        for d in info["decisions"]:
            rid = "%s-AD%d" % (a["key"], d["n"])
            f = d["fields"]
            status, sup_by = "accepted", None
            if f.get("Withdrawn"):
                status = "withdrawn"
            elif f.get("Superseded by"):
                status, sup_by = "superseded", "%s-AD%s" % (a["key"], CITE_RE.search(f["Superseded by"]).group(1))
            records[rid] = {"id": rid, "n": d["n"], "title": d["title"], "status": status, "own": status,
                            "superseded_by": sup_by, "scope": a["scope"], "group": a["group"], "epic": a["epic"],
                            "source": a["path"], "ard_title": info["title"], "components": comps,
                            "tags": sorted(set(comps) | set(s for s in slugs if s)), "fields": f,
                            "applied": set(), "deviated": [], "cross": None, "line": d["line"]}

    ard_name = VI_ARD_RE if layout == "vi" else PRD_ARD_RE
    for folder, group in sorted({(a["folder"], a["group"]) for a in ards}):
        prefix = folder + "/"
        for p in files:
            if (not p.startswith(prefix) or not p.endswith(".md") or excluded(p)
                    or ard_name.match(p.rsplit("/", 1)[-1])):
                continue
            pdir = os.path.dirname(p)
            dirs = [k for k in by_dir if k.startswith(prefix) and (pdir == k or pdir.startswith(k + "/"))]
            entry = by_dir[max(dirs, key=len)] if dirs else None
            is_design = p.rsplit("/", 1)[-1] == "design.md"
            for i, ln in enumerate(read(root, sha, p).split("\n"), 1):
                m = DEVIATION_RE.match(ln)
                cites = [(int(m.group(1)), m)] if m else (
                    [(int(c.group(1)), None) for c in CITE_RE.finditer(ln)] if is_design else [])
                for n, dev in cites:
                    a, ambiguous = resolve_citation(n, entry, group_ard.get(group), parsed)
                    if ambiguous:
                        problems.append(problem("ambiguous-citation", p, i,
                                                "[AD#%d] is in more than one area ARD of this Epic" % n))
                        continue
                    rid = "%s-AD%d" % (a["key"], n) if a else None
                    if rid not in records:
                        continue
                    if dev:
                        rest = re.sub(r"^[—–-]+\s*", "", dev.group(2))
                        records[rid]["deviated"].append((p, re.sub(r"\s*[—–-]+\s*flag:\s*\S+\s*$", "", rest)))
                    else:
                        records[rid]["applied"].add(p)

    claims = {}
    for r in sorted(records.values(), key=lambda x: natural(x["id"])):
        for v in r["fields"]["Supersedes"]:
            carriers = claims.setdefault(SUPERSEDES_RE.match(v).group(2), [])
            if r not in carriers:  # one decision naming a record twice is one claim
                carriers.append(r)
    for target in sorted(claims, key=natural):
        live = []
        for r in claims[target]:
            t = records.get(target)
            if r["own"] != "accepted":
                why = ("supersedes-carrier-not-live", "%s is %s, so its Supersedes of %s is not applied"
                       % (r["id"], r["own"], target))
            elif t is None:
                why = ("supersedes-missing-target", "%s names %s, which no parseable ARD on this ref holds"
                       % (r["id"], target))
            elif t["group"] == r["group"]:
                why = ("supersedes-same-group", "%s and %s share %s %s — refine that ARD with Superseded by instead"
                       % (r["id"], target, group_word, r["group"]))
            elif t["own"] != "accepted":
                why = ("supersedes-target-not-accepted", "%s names %s, which is already %s"
                       % (r["id"], target, t["own"]))
            else:
                why = None
            if why:
                problems.append(problem(why[0], r["source"], r["line"], why[1]))
            else:
                live.append(r)
        if len(live) > 1:
            t = records[target]
            problems.append(problem("supersede-conflict", t["source"], t["line"], "%s is superseded by %s — neither is applied"
                                    % (target, " and ".join(x["id"] for x in live))))
        elif live:
            t, r = records[target], live[0]
            t["status"], t["superseded_by"] = "superseded", r["id"]
            t["cross"] = "**Superseded by:** [%s %s](%s.md)" % (r["id"], r["title"], r["id"])

    decisions_dir = KB + "/decisions/"
    old = {p[len(decisions_dir):-3]: read(root, sha, p) for p in files
           if p.startswith(decisions_dir) and p.endswith(".md") and "/" not in p[len(decisions_dir):]}
    texts, entries = {}, []
    for rid in sorted(records, key=natural):
        r, o = records[rid], old.get(rid)
        preserved = []
        if o is not None:
            order, blocks = fm_blocks(split_frontmatter(o)[0])
            preserved = [blocks[k] for k in order if k not in OWNED]
        new = render_record(r, preserved, group_key)
        if o is None:
            kind = "create"
        elif o == new:
            kind = "unchanged"
        else:
            was = fm_scalar(fm_blocks(split_frontmatter(o)[0])[1], "status")
            kind = ("supersede" if r["status"] == "superseded" and was != "superseded" else
                    "withdraw" if r["status"] == "withdrawn" and was != "withdrawn" else "update")
        plan[kind].append(rid)
        if kind != "unchanged":
            texts[decisions_dir + rid + ".md"] = new
        entries.append({"id": rid, "title": r["title"], "status": r["status"], "tags": r["tags"], "group": r["group"]})
    for rid in sorted((k for k in old if k not in records), key=natural):
        plan["kept"].append(rid)
        _, b = fm_blocks(split_frontmatter(old[rid])[0])
        src = fm_scalar(b, "source")
        if src not in present:
            problems.append(problem("source-missing", decisions_dir + rid + ".md", 0,
                                    "its source %s is not on this ref; the record is kept unchanged" % src))
        elif not any(pr["file"] == src for pr in problems):
            problems.append(problem("decision-missing", decisions_dir + rid + ".md", 0,
                                    "its decision is no longer in %s; the record is kept unchanged" % src))
        entries.append({"id": rid, "title": fm_scalar(b, "title", strip_comment=False) or rid,
                        "status": fm_scalar(b, "status") or "accepted", "tags": fm_list(b, "tags"),
                        "group": fm_scalar(b, group_key) or ""})
    entries.sort(key=lambda e: natural(e["id"]))
    if entries:
        for path, body in ((KB + "/index.yaml", render_index(entries)),
                           (KB + "/README.md", render_readme(entries, group_word))):
            if (read(root, sha, path) if path in present else None) != body:
                texts[path] = body
    plan["files"] = sorted(texts)
    plan["live"] = sum(1 for e in entries if e["status"] == "accepted")
    if write:
        base = os.path.realpath(os.path.join(root, KB))
        for path in plan["files"]:
            full = os.path.join(root, path)
            if not os.path.realpath(full).startswith(base + os.sep):
                raise Abort("refusing to write %s: it resolves outside %s" % (path, base))
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(texts[path])
    return plan


def tree(root, rev):
    r = subprocess.run(["git", "-C", root, "rev-parse", "--verify", "--quiet", "%s:%s" % (rev, KB)],
                       stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    return r.stdout.decode().strip() if r.returncode == 0 else None


def pending_kb(root, ref):
    """The kb/ branches not yet on <ref>: neither an ancestor of it, nor carrying an architecture/ tree
    some commit of <ref> has held — a squash or rebase merge lands the tree without the ancestry."""
    sha = resolve(root, ref)
    landed = {tree(root, c) for c in git(root, "log", "--format=%H", sha, "--", KB).split()}
    pending = []
    for b in git(root, "for-each-ref", "--format=%(refname:short)", "refs/heads/kb", "refs/remotes/origin/kb").split():
        if subprocess.run(["git", "-C", root, "merge-base", "--is-ancestor", b, sha],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0:
            continue
        t = tree(root, b)
        if t is None or t not in landed:
            pending.append(b)
    return pending


def summary(plan):
    if plan["no_ards"]:
        return "no ARD on %s; %d problems" % (plan["ref"], len(plan["problems"]))
    counts = tuple(len(plan[k]) for k in ("create", "update", "supersede", "withdraw", "unchanged", "kept"))
    return ("%d to create, %d to update, %d to supersede, %d to withdraw, %d unchanged, %d kept; " % counts
            + "%d problems; %d live records" % (len(plan["problems"]), plan["live"]))


def selftest():
    """Every rule of the architecture-kb reference, on fixtures built at run time."""
    failures = []
    me = os.path.abspath(__file__)

    def check(ok, what):
        if not ok:
            failures.append(what)

    dash = "AD" + "-"  # the legacy heading, assembled so this file never holds the dash form whole

    def ad(n, title, rule=True, extra=(), legacy=False):
        out = ["### [%s%d]: %s" % (dash if legacy else "AD#", n, title), "",
               "**Binds:** the %s path." % title.lower(), "", "**Prevents:** divergence %d." % n, ""]
        if rule:
            out += ["**Rule:** %s holds." % title, ""]
        out += ["**Alternatives:** option B — lost on cost.", ""]
        out += list(extra)
        return "\n".join(out) + "\n"

    def ard(title, decisions, fm=""):
        return ("---\ntitle: %s — ARD\n%s---\n\n# %s — ARD\n\n## Context\n\nWhy.\n\n## Architecture decisions\n\n%s\n"
                "## Open questions\n\nNone.\n") % (title, fm, title, "\n".join(decisions))

    def sup(target, title):
        return "**Supersedes:** [%s %s](../../architecture/decisions/%s.md) — one rule for every service." % (
            target, title, target)

    def git(tmp, *args):
        subprocess.run(["git", "-C", tmp, *args], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def init(tmp):
        git(tmp, "init", "-q")
        git(tmp, "config", "user.email", "t@example.invalid")
        git(tmp, "config", "user.name", "t")
        git(tmp, "config", "commit.gpgsign", "false")

    def commit(tmp, files, message):
        for rel, body in files.items():
            path = os.path.join(tmp, rel)
            if body is None:
                os.remove(path)
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(body)
        git(tmp, "add", "-A")
        git(tmp, "commit", "-q", "-m", message)

    def text(tmp, rel):
        path = os.path.join(tmp, rel)
        if not os.path.exists(path):
            return ""
        with open(path, encoding="utf-8") as fh:
            return fh.read()

    def kinds(plan):
        return [p["kind"] for p in plan["problems"]]

    def cli(*args, env=None):
        return subprocess.run([sys.executable, me, *args], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              env=dict(os.environ, **(env or {})))

    # ---- the vi layout ---------------------------------------------------------------
    vi = "specifications/ACME-1-orders/"
    epic = vi + "ACME-2-checkout/"
    design = epic + "design.md"
    vi_fm = 'components:\n  - id: orders\n  - id: "shop:web"\n    kind: code\ngrounded_repos:\n  - shop @ /work/shop\n'

    def orders(third=False):
        return ard("Orders", [
            ad(1, "Orders publish events through an outbox"),
            ad(2, "Cache per node", extra=["**Superseded by:** [AD#3] — a shared cache wins.", ""]),
            ad(3, "Shared cache", extra=(["**Superseded by:** [AD#6] — v2.", ""] if third else [])),
            ad(4, "Nightly export", extra=["**Withdrawn:** scope cut.", ""]),
            ad(5, "Legacy form", legacy=True)] + ([ad(6, "Cache v2")] if third else []), vi_fm)

    def billing(third=False):
        return ard("Billing", [
            ad(1, "Billing writes through the outbox library",
               extra=[sup("ACME-1-AD1", "Orders publish events through an outbox"), ""]),
            ad(2, "Billing cache", extra=[sup("ACME-1-AD2", "Cache per node"), ""]),
            ad(3, "Billing ledger", extra=[sup("ACME-9-AD1", "Missing"), ""]),
            ad(4, "Billing export", extra=["**Withdrawn:** dropped.", "", sup("ACME-1-AD3", "Shared cache"), ""]),
            ad(5, "Billing retries", extra=[sup("ACME-7-AD6", "Billing idempotency"), ""]),
            ad(6, "Billing idempotency", extra=(["**Withdrawn:** moot.", ""] if third else []))])

    first = {
        vi + "ACME-1_ARD.md": orders(),
        epic + "ACME-2_ARD.md": ard("Checkout", [
            "### Inherited invariants\n\n- [AD#1] — Orders publish events through an outbox\n",
            ad(1, "Checkout uses idempotency keys")]),
        epic + "ACME-2-ui_ARD.md": ard("Checkout UI", [ad(2, "UI renders server errors"), ad(4, "UI caches drafts")]),
        epic + "ACME-2-api_ARD.md": ard("Checkout API", [ad(4, "API caches drafts")]),
        design: ("# Design\n\nUses [AD#1] and [AD#3]; renders per [AD#2]; drafts per [AD#4].\n\n## ARD deviations\n\n"
                 "- ARD deviation: [AD#3] — caches per pod — latency budget — flag: architect\n"),
        vi + "revisions/design.md": "Cites [AD#1].\n",
        vi + "tracker-import/ACME-2.md": "- ARD deviation: [AD#3] — copied into a tracker export — flag: architect\n",
        "specifications/ACME-7-billing/ACME-7_ARD.md": billing(),
        "specifications/ACME-8-bad/ACME-8_ARD.md": ard("Bad", [
            ad(1, "No rule", rule=False), ad(2, "Twice"), ad(2, "Twice again"),
            "### [AD#]: No number\n\n**Rule:** x.\n",
            ad(3, "Bad link", extra=["**Supersedes:** [the outbox decision](x.md) — why.", ""]),
            ad(4, "Both", extra=["**Superseded by:** [AD#3] — x.", "", "**Withdrawn:** y.", ""]),
            ad(5, "No target", extra=["**Superseded by:** the next one.", ""]),
            ad(6, "Dangling", extra=["**Superseded by:** [AD#42] — gone.", ""]),
            "### AD#9: No brackets\n\n**Rule:** x.\n",
            "### [AD#7] No colon\n\n**Rule:** y.\n"]),
        "specifications/ACME-10-zahlungsauslösung/ACME-10_ARD.md": ard("Zahlung", [
            ad(1, "A wins", extra=[sup("ACME-1-AD5", "Legacy form"), ""]), ad(2, "Unruled", rule=False)]),
        "specifications/ACME-11-b/ACME-11_ARD.md": ard("B", [ad(1, "B wins", extra=[sup("ACME-1-AD5", "Legacy form"), ""])]),
        "specifications/ACME-12-a/ACME-12_ARD.md": ard("First", [ad(1, "First")]),
        "specifications/ACME-12-b/ACME-12_ARD.md": ard("Second", [ad(1, "Second")]),
        "specifications/ACME-13_gone/ACME-13_ARD.md": ard("Gone", [ad(1, "Soon gone")]),
        "specifications/ACME-5-csv-import/ACME-5_ARD.md": ard("CSV import", [ad(1, "Imports stream")]),
        "specifications/ACME-5-csv-import/ACME-6-bulk-import/ACME-6_ARD.md": ard("Bulk", [ad(1, "Bulk imports batch")]),
        "specifications/ACME-15-caps/ACME-15_ARD.md": ard("Caps", [ad(1, "Headings drift")]).replace(
            "## Architecture decisions", "## 3. Architecture Decisions"),
        "specifications/ACME-16-none/ACME-16_ARD.md": ard("None", [ad(1, "Lost")]).replace(
            "## Architecture decisions", "## Decisions"),
        "specifications/ACME-17-twice/ACME-17_ARD.md": ard("Twice", [ad(1, "Says it twice", extra=[
            sup("ACME-15-AD1", "Headings drift"), "", sup("ACME-15-AD1", "Headings drift"), ""])]),
        "specifications/ACME-18-bullets/ACME-18_ARD.md": ard("Bullets", [
            "### [AD#1]: Bulleted fields\n\n- **Binds:** the bulleted path.\n- **Prevents:** drift.\n"
            "- **Rule:** Bullets hold.\n- **Alternatives:** prose — lost.\n"]),
        "specifications/notes/ACME-19_ARD.md": ard("Loose", [ad(1, "Unfiled")]),
    }
    with tempfile.TemporaryDirectory() as tmp:
        init(tmp)
        commit(tmp, first, "ARDs")

        def rec(rid):
            return text(tmp, "%s/decisions/%s.md" % (KB, rid))

        p1 = harvest(tmp, "HEAD", "vi", write=True)
        expect = {"ACME-1-AD1", "ACME-1-AD2", "ACME-1-AD3", "ACME-1-AD4", "ACME-1-AD5", "ACME-2-AD1",
                  "ACME-2-ui-AD2", "ACME-2-ui-AD4", "ACME-2-api-AD4", "ACME-7-AD1", "ACME-7-AD2", "ACME-7-AD3",
                  "ACME-7-AD4", "ACME-7-AD5", "ACME-7-AD6", "ACME-10-AD1", "ACME-11-AD1", "ACME-13-AD1",
                  "ACME-5-AD1", "ACME-6-AD1", "ACME-15-AD1", "ACME-17-AD1", "ACME-18-AD1"}
        check(set(p1["create"]) == expect, "first harvest creates exactly the parseable decisions: %s" % sorted(
            set(p1["create"]) ^ expect))
        check(not (p1["update"] or p1["supersede"] or p1["withdraw"] or p1["kept"]), "first harvest only creates")
        check(p1["live"] == 18, "18 live records, got %s" % p1["live"])
        check("superseded_by: ACME-17-AD1" in rec("ACME-15-AD1") and not any(
            x["kind"] == "supersede-conflict" and "ACME-15-AD1" in x["detail"] for x in p1["problems"]),
              "two identical Supersedes lines on one decision are one claim, not a conflict")
        check("**Binds:** the bulleted path.\n\n**Prevents:**" in rec("ACME-18-AD1") and "\n-\n" not in rec("ACME-18-AD1"),
              "bullet-form fields leave no stray bullet marker")
        check(any(x["file"] == "specifications/notes/ACME-19_ARD.md" and x["kind"] == "unparseable" for x in p1["problems"]),
              "an ARD outside a keyed folder is reported")
        r = cli("--specs", tmp, "--ref", "HEAD", "--dry-run", env={"PYTHONIOENCODING": "ascii"})
        try:
            asc = json.loads(r.stdout.decode("ascii"))
        except (ValueError, UnicodeDecodeError):
            asc = {}
        check("specifications/ACME-10-zahlungsauslösung/ACME-10_ARD.md" in json.dumps(asc, ensure_ascii=False),
              "the plan is valid JSON on an ASCII-only stdout")
        check(any(x["file"].startswith("specifications/ACME-16-none/") and x["kind"] == "unparseable" for x in p1["problems"]),
              "an ARD with no Architecture decisions section is reported")
        bad8 = [p for p in p1["problems"] if p["file"].startswith("specifications/ACME-8-bad/")]
        check([p["kind"] for p in bad8] == ["unparseable"] * 9,
              "ACME-8: no Rule, a duplicate, no number, a bad Supersedes, superseded and withdrawn, Superseded by "
              "with no [AD#M] or naming one the ARD lacks, no brackets, no colon — got %s" % [p["detail"] for p in bad8])
        details = " | ".join(p["detail"] for p in bad8)
        check("brackets" in details and "colon" in details and "does not hold" in details,
              "each heading form and a dangling Superseded by is named for what it is: %s" % details)
        for kind in ("key-conflict", "supersedes-missing-target", "supersedes-same-group",
                     "supersedes-target-not-accepted", "supersedes-carrier-not-live", "supersede-conflict",
                     "ambiguous-citation"):
            check(kind in kinds(p1), "problem %s reported" % kind)
        check(kinds(p1).count("key-conflict") == 2, "a key conflict names both ARDs")
        check("status: superseded" in rec("ACME-1-AD1") and "superseded_by: ACME-7-AD1" in rec("ACME-1-AD1")
              and "**Superseded by:** [ACME-7-AD1 Billing writes through the outbox library](ACME-7-AD1.md)"
              in rec("ACME-1-AD1"), "a cross-VI Supersedes supersedes its target")
        check("superseded_by: ACME-1-AD3" in rec("ACME-1-AD2"), "Superseded by within one ARD")
        check("status: withdrawn" in rec("ACME-1-AD4"), "Withdrawn")
        check("status: accepted" in rec("ACME-1-AD5"), "the legacy dash form is harvested; a conflict applies neither")
        check("status: accepted" in rec("ACME-1-AD3"), "a withdrawn decision's Supersedes is not applied")
        check(design in rec("ACME-2-AD1") and design not in rec("ACME-1-AD1"), "the Epic ARD wins a citation")
        check(design in rec("ACME-1-AD3") and design in rec("ACME-2-ui-AD2"), "else one area ARD, else the VI's")
        check(design not in rec("ACME-2-ui-AD4") and design not in rec("ACME-2-api-AD4"), "ambiguous links neither")
        check("— caches per pod — latency budget" in rec("ACME-1-AD3") and "flag: architect" not in rec("ACME-1-AD3"),
              "Deviated in carries what and why")
        check("revisions" not in rec("ACME-1-AD1"), "revisions/ is never scanned")
        check("tracker-import" not in rec("ACME-1-AD3"), "a tracker export (*-import/) is never scanned")
        check('components: ["orders", "shop:web"]' in rec("ACME-2-AD1") and '"shop"' in rec("ACME-1-AD3"),
              "an Epic record takes the VI's components; a record's tags carry its ARD's repo slugs")
        check(len([i for i in p1["create"] if i.startswith("ACME-2-AD")]) == 1, "inherited invariants not harvested")
        check("](ACME-1-AD1.md)" in rec("ACME-7-AD1"), "a Supersedes link is re-targeted to the record")
        check("specifications/ACME-10-zahlungsauslösung/ACME-10_ARD.md" in rec("ACME-10-AD1"), "non-ASCII paths raw")
        check("vi: ACME-13" in rec("ACME-13-AD1"), "a folder with _ drift keeps its key")
        check("  - id: ACME-1-AD3" in text(tmp, KB + "/index.yaml"), "index.yaml lists the records")
        readme = text(tmp, KB + "/README.md")
        check("[ACME-1-AD3](decisions/ACME-1-AD3.md)" in readme and "[ACME-1-AD1](decisions/" not in readme,
              "README lists live records only")

        commit(tmp, {}, "harvest")
        p2 = harvest(tmp, "HEAD", "vi", write=True)
        check(not (p2["create"] or p2["update"] or p2["supersede"] or p2["withdraw"] or p2["files"]),
              "a second harvest on an unchanged ref changes nothing: %s" % p2["files"])

        kept13 = rec("ACME-13-AD1")
        a2 = rec("ACME-2-AD1").replace("---\n<!--", "promotion: proposed\n---\n<!--", 1)
        a2 = a2.replace("Checkout uses idempotency keys holds.", "Hand edit.")
        commit(tmp, {vi + "ACME-1_ARD.md": orders(third=True),
                     "specifications/ACME-7-billing/ACME-7_ARD.md": billing(third=True),
                     "specifications/ACME-13_gone/ACME-13_ARD.md": None,
                     "specifications/ACME-5-csv-import/ACME-5_ARD.md": ard("CSV import", [ad(2, "Imports batch")]),
                     KB + "/decisions/ACME-2-AD1.md": a2}, "third")
        commit_free = "specifications/ACME-14-new/ACME-14_ARD.md"
        os.makedirs(os.path.join(tmp, os.path.dirname(commit_free)))
        with open(os.path.join(tmp, commit_free), "w", encoding="utf-8") as fh:
            fh.write(ard("New", [ad(1, "Uncommitted")]))
        p3 = harvest(tmp, "HEAD", "vi", write=True)
        check(p3["supersede"] == ["ACME-1-AD3"], "supersede: %s" % p3["supersede"])
        check(p3["withdraw"] == ["ACME-7-AD6"], "withdraw: %s" % p3["withdraw"])
        check(p3["create"] == ["ACME-1-AD6", "ACME-5-AD2"], "create: %s" % p3["create"])
        check(p3["update"] == ["ACME-2-AD1"], "update: %s" % p3["update"])
        check(p3["kept"] == ["ACME-5-AD1", "ACME-13-AD1"] and "source-missing" in kinds(p3), "a vanished source keeps its record: %s" % p3["kept"])
        check("decision-missing" in kinds(p3), "a decision gone from its ARD keeps its record and is reported")
        check(rec("ACME-13-AD1") == kept13, "a kept record is byte-identical")
        check("ACME-14" not in json.dumps(p3), "an uncommitted ARD is never read")
        check("promotion: proposed" in rec("ACME-2-AD1") and "Checkout uses idempotency keys holds." in rec("ACME-2-AD1")
              and "Hand edit." not in rec("ACME-2-AD1"), "foreign keys survive; owned content is regenerated")
        check("  - id: ACME-13-AD1" in text(tmp, KB + "/index.yaml"), "a kept record stays in the index")

    # ---- nothing to harvest, and the exit codes -----------------------------------------
    with tempfile.TemporaryDirectory() as tmp:
        init(tmp)
        commit(tmp, {"specifications/ACME-3-x/idea.md": "# Idea\n"}, "idea")
        p = harvest(tmp, "HEAD", "vi", write=True)
        check(p["no_ards"] and not p["files"] and not os.path.exists(os.path.join(tmp, KB)), "no ARD writes nothing")
        check(cli("--specs", tmp, "--ref", "nosuchref").returncode == 2, "an unknown ref exits 2")
    with tempfile.TemporaryDirectory() as tmp:
        check(cli("--specs", tmp, "--ref", "HEAD").returncode == 2, "outside a git repository exits 2")

    # ---- unmerged kb/ branches: ancestry, a squash merge, a later harvest -----------------
    with tempfile.TemporaryDirectory() as tmp:
        init(tmp)
        commit(tmp, {"README.md": "x\n"}, "base")
        git(tmp, "branch", "-M", "main")
        git(tmp, "checkout", "-q", "-b", "kb/harvest-a")
        commit(tmp, {KB + "/a.md": "a\n"}, "a")
        git(tmp, "checkout", "-q", "main")
        git(tmp, "checkout", "-q", "-b", "kb/harvest-b")
        commit(tmp, {KB + "/b.md": "b\n"}, "b")
        git(tmp, "checkout", "-q", "main")
        git(tmp, "merge", "-q", "--no-ff", "-m", "merge b", "kb/harvest-b")
        git(tmp, "checkout", "-q", "-b", "kb/harvest-c")
        commit(tmp, {KB + "/c.md": "c\n"}, "c")
        git(tmp, "checkout", "-q", "main")
        git(tmp, "merge", "-q", "--squash", "kb/harvest-c")
        git(tmp, "commit", "-q", "-m", "squash c")
        commit(tmp, {KB + "/d.md": "d\n"}, "a later harvest")
        check(pending_kb(tmp, "main") == ["kb/harvest-a"],
              "only the unmerged kb/ branch is pending — not one merged by ancestry or squash: %s" % pending_kb(tmp, "main"))
        r = cli("--specs", tmp, "--ref", "main", "--pending-kb")
        check(r.returncode == 0 and json.loads(r.stdout.decode("utf-8") or "{}").get("pending") == ["kb/harvest-a"],
              "--pending-kb prints the pending branches")

    # ---- the prd layout -----------------------------------------------------------------
    with tempfile.TemporaryDirectory() as tmp:
        init(tmp)
        shop = "specifications/PRD-ACME-90-shop/"
        cart = shop + "EPIC-ACME-90-01-cart/"
        commit(tmp, {
            shop + "prd.md": "---\nkey: ACME-90\n---\n# Shop\n",
            shop + "ard.md": ard("Shop", [ad(1, "Shop uses one database")],
                                 "key: ACME-90\nkind: ard\ncomponents:\n  - id: shop\n"),
            cart + "ard.md": ard("Cart", [ad(1, "Cart keeps sessions server-side")], "key: ACME-90-01\nkind: ard\n"),
            cart + "ard-ui.md": ard("Cart UI", [ad(1, "Cart UI is optimistic")], "key: ACME-90-01\nkind: ard\n"),
            cart + "design.md": "# Design\n\nPer [AD#1].\n",
            "specifications/PRD-ACME-2-data-import/ard.md": ard("Data", [ad(1, "Data lands raw")], "key: ACME-2\nkind: ard\n"),
            "specifications/PRD-ACME-3-evil/ard.md": ard("Evil", [ad(1, "Escapes")], "key: ../../../escape/pwn\nkind: ard\n"),
            "specifications/PRD-ACME-91-pay/ard.md": ard("Pay", [ad(
                1, "Payments share the shop database", extra=[sup("ACME-90-AD1", "Shop uses one database"), ""])],
                "key: ACME-91\nkind: ard\n"),
        }, "prd fixtures")
        r = cli("--specs", tmp, "--ref", "HEAD", "--layout", "prd", "--dry-run")
        try:
            dry = json.loads(r.stdout.decode("utf-8"))
        except ValueError:
            dry = {"create": []}
        check(r.returncode == 0 and set(dry["create"]) == {"ACME-90-AD1", "ACME-90-01-AD1", "ACME-90-01-ui-AD1",
                                                             "ACME-91-AD1", "ACME-2-AD1"}, "prd layout dry run: %s" % dry.get("create"))
        check(all(".." not in f for f in dry.get("files", [])) and any(
            x["file"].startswith("specifications/PRD-ACME-3-evil/") and x["kind"] == "unparseable" for x in dry.get("problems", [])),
              "a frontmatter key that is not a key is unparseable, never a path")
        check(not os.path.exists(os.path.join(tmp, KB)), "--dry-run writes nothing")
        harvest(tmp, "HEAD", "prd", write=True)

        def prec(rid):
            return text(tmp, "%s/decisions/%s.md" % (KB, rid))

        check("scope: prd" in prec("ACME-90-AD1") and "prd: ACME-90" in prec("ACME-90-AD1")
              and "superseded_by: ACME-91-AD1" in prec("ACME-90-AD1"), "prd: scope, group and a cross-PRD Supersedes")
        check("scope: epic" in prec("ACME-90-01-AD1") and "epic: ACME-90-01" in prec("ACME-90-01-AD1")
              and cart + "design.md" in prec("ACME-90-01-AD1"), "prd: an Epic record and its citation")
        check('components: ["shop"]' in prec("ACME-90-01-AD1"), "prd: components from the PRD-level ARD")
        check("scope: area" in prec("ACME-90-01-ui-AD1") and cart + "design.md" not in prec("ACME-90-01-ui-AD1"),
              "prd: an area record; the Epic ARD wins its citation")

    if failures:
        print("architecture-harvest selftest: FAIL")
        for f in failures:
            print("  " + f)
        return 1
    print("architecture-harvest selftest: PASS")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Harvest ARD decisions into the team architecture knowledge base.")
    ap.add_argument("--specs", help="the specs repository's top level")
    ap.add_argument("--ref", help="the ref to read: the specs repository's default branch, or a commit")
    ap.add_argument("--layout", choices=sorted(GROUP), default="vi", help="vi (<KEY>_ARD.md) or prd (ard.md)")
    ap.add_argument("--dry-run", action="store_true", help="print the plan and write nothing")
    ap.add_argument("--pending-kb", action="store_true", help="print the kb/ branches not yet on --ref, and exit")
    ap.add_argument("--selftest", action="store_true", help="run the built-in fixtures and exit")
    a = ap.parse_args()
    try:
        sys.stdout.reconfigure(errors="backslashreplace")
    except AttributeError:
        pass
    if a.selftest:
        return selftest()
    if not a.specs or not a.ref:
        print("architecture-harvest: --specs and --ref are required", file=sys.stderr)
        return 2
    try:
        if a.pending_kb:
            print(json.dumps({"pending": pending_kb(a.specs, a.ref)}, indent=2))
            return 0
        plan = harvest(a.specs, a.ref, a.layout, write=not a.dry_run)
    except Exception as e:  # anything unexpected is "could not run", never a partial plan
        print("architecture-harvest: not run (%s: %s)" % (type(e).__name__, e), file=sys.stderr)
        return 2
    print(json.dumps(plan, indent=2))  # ASCII-escaped: valid JSON on any stdout encoding
    print(summary(plan), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
